src/main/java/controller/PacienteController.java
package controller;

import gestion.PacienteGestion;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.nio.file.Files;
import java.util.List;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletResponse;
import modelo.Paciente;



@Named(value = "pacienteController")
@SessionScoped
public class PacienteController extends Paciente implements Serializable {

    public PacienteController() {
    }

    public String insertaAdmin() {

        if (PacienteGestion.insertar(this)) {
            return "listaPAdmin.xhtml";

        } else {

            FacesMessage mensaje = new FacesMessage(FacesMessage.SEVERITY_ERROR,
                    "Error", "Posible identificación duplicada");
            FacesContext.getCurrentInstance().addMessage("editaPacientesForm:identificacion", mensaje);
            return "editaPAdmin.xhtml";
        }

    }
    
    public String insertaUser() {

        if (PacienteGestion.insertar(this)) {
            return "listaPUser.xhtml";

        } else {

            FacesMessage mensaje = new FacesMessage(FacesMessage.SEVERITY_ERROR,
                    "Error", "Posible identificación duplicada");
            FacesContext.getCurrentInstance().addMessage("editaPacientesForm:identificacion", mensaje);
            return "editaPUser.xhtml";
        }

    }

    public List<Paciente> getPacientes(){
        
        return PacienteGestion.getPacientes();   
    } 
    
    public void buscaPaciente(String id){

        Paciente paciente = PacienteGestion.getPaciente(id);

        if (paciente!= null){
            this.setIdPaciente(paciente.getIdPaciente());
            this.setNombreP(paciente.getNombreP());
            this.setApellido1(paciente.getApellido1());
            this.setApellido2(paciente.getApellido2());
            
        }else {
            this.setIdPaciente("");
            this.setNombreP("");
            this.setApellido1("");
            this.setApellido2("");
           

            FacesMessage mensaje = new FacesMessage(FacesMessage.SEVERITY_WARN, "No Encontrado",
            "Paciente No Encontrado");
            FacesContext.getCurrentInstance().addMessage("pacienteForm:idExpediente", mensaje);
        }
    }
    
     public void respaldoPacientes(){
        
        String json  = PacienteGestion.GenerarJson();
        try{
            File f = new File (FacesContext.getCurrentInstance().getExternalContext().getRealPath("/respaldo")+"PacientesRegistrados.zip");
            ZipOutputStream out = new ZipOutputStream (new FileOutputStream(f));
            ZipEntry e = new ZipEntry ("PacientesRegistrados.json");
            try{     
                out.putNextEntry(e);
                byte[] data =json.getBytes();
                out.write(data,0,data.length);
                out.closeEntry();
                out.close();

                File zipPath = new File (FacesContext.getCurrentInstance().getExternalContext()
                .getRealPath("/respaldo")+"PacientesRegistrados.zip");
                
                byte[] zip = Files.readAllBytes(zipPath.toPath());
                
                HttpServletResponse respuesta = (HttpServletResponse)
                    FacesContext.getCurrentInstance().getExternalContext().getResponse();
                
                ServletOutputStream sos = respuesta.getOutputStream();
            
                respuesta.setContentType("application/zip");
                respuesta.addHeader("Content-Disposition","attachment; filename=PacientesRegistrados.zip");
                
                sos.write(zip);
                sos.flush();
                FacesContext.getCurrentInstance().responseComplete();
                
            }catch (IOException ex){

            }
        }
        catch(FileNotFoundException ex){
        }
    }
}

src/main/webapp/Paciente/ingresaPAdmin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">

    <body>
        <ui:composition template="../resources/plantillas/plantillaAdmin.xhtml">
            <ui:define name="content">
                <h:form id="editaPacientesForm">
                    <b:panel title="Paciente" look="primary">
                        <b:row tooltip="La identificación no se modifica">
                            <b:column medium-screen="2">
                                <h:outputLabel value="Identificación" for="identificacion"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Identificacion" id="identificacion"
                                             required="true"
                                             value="#{pacienteController.idPaciente}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="identificacion"/>
                            </b:column>
                        </b:row>
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Habitación" for="habitacion"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Habitación" id="habitacion"
                                             required="true"
                                             value="#{pacienteController.idHabitacion}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="habitacion"/>
                            </b:column>
                        </b:row>
                        <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Nombre" for="nombre"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Nombre" id="nombre"
                                             required="true"
                                             value="#{pacienteController.nombreP}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="nombre"/>
                            </b:column>
                        </b:row>
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Primer Apellido" for="apellido1"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Primer Apellido" id="apellido1"
                                             required="true"
                                             value="#{pacienteController.apellido1}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="apellido1"/>
                            </b:column>
                        </b:row>
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Segundo Apellido" for="apellido2"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Segundo Apellido" id="apellido2"
                                             required="true"
                                             value="#{pacienteController.apellido2}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="apellido2"/>
                            </b:column>
                        </b:row>
                        <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Dirección" for="direccion"/>
                            </b:column>
                            <b:column medium-screen="4">
                                 <b:inputText placeholder="Direccion" id="direccion"
                                             required="true"
                                             value="#{pacienteController.direccPaciente}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="direccion"/>
                            </b:column>
                        </b:row>
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Género" for="genero"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:panelGrid size="" columns="2">
                                    <b:radiobutton value="#{pacienteController.genero}"
                                                   itemLabel="Masculino"
                                                   itemValue="M"/>
                                    <b:radiobutton value="#{pacienteController.genero}"
                                                   itemLabel="Femenino"
                                                   itemValue="F"/>
                                </b:panelGrid>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="genero"/>
                            </b:column>
                        </b:row>
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Número de Teléfono" for="numTel"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Número de Teléfono" id="numTel"
                                             required="true"
                                             value="#{pacienteController.numTel}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="numTel"/>
                            </b:column>
                        </b:row>
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Fecha de nacimiento" for="fechaNaci"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:datepicker id="fechaNaci"
                                              required="true"
                                              value="#{pacienteController.fechaNaci}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="fechaNaci"/>
                            </b:column>
                        </b:row>
                        <b:row>
                            <b:column medium-screen="2"/>
                            <b:column medium-screen="6">
                                <b:commandButton value="Insertar"
                                                 action="#{pacienteController.insertaAdmin()}"
                                                 look="primary"
                                                 style="width: 33%"/>
                            </b:column>   
                        </b:row>    
                    </b:panel>
                </h:form> 
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/Paciente/ingresaPUser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">

    <body>
        <ui:composition template="../resources/plantillas/plantillaUser.xhtml">
            <ui:define name="content">
                <h:form id="editaPacientesForm">
                    <b:panel title="Paciente" look="primary">
                        <b:row tooltip="La identificación no se modifica">
                            <b:column medium-screen="2">
                                <h:outputLabel value="Identificación" for="identificacion"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Identificacion" id="identificacion"
                                             required="true"
                                             value="#{pacienteController.idPaciente}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="identificacion"/>
                            </b:column>
                        </b:row>
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Habitación" for="habitacion"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Habitación" id="habitacion"
                                             required="true"
                                             value="#{pacienteController.idHabitacion}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="habitacion"/>
                            </b:column>
                        </b:row>
                        <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Nombre" for="nombre"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Nombre" id="nombre"
                                             required="true"
                                             value="#{pacienteController.nombreP}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="nombre"/>
                            </b:column>
                        </b:row>
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Primer Apellido" for="apellido1"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Primer Apellido" id="apellido1"
                                             required="true"
                                             value="#{pacienteController.apellido1}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="apellido1"/>
                            </b:column>
                        </b:row>
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Segundo Apellido" for="apellido2"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Segundo Apellido" id="apellido2"
                                             required="true"
                                             value="#{pacienteController.apellido2}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="apellido2"/>
                            </b:column>
                        </b:row>
                        <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Dirección" for="direccion"/>
                            </b:column>
                            <b:column medium-screen="4">
                                 <b:inputText placeholder="Direccion" id="direccion"
                                             required="true"
                                             value="#{pacienteController.direccPaciente}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="direccion"/>
                            </b:column>
                        </b:row>
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Género" for="genero"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:panelGrid size="" columns="2">
                                    <b:radiobutton value="#{pacienteController.genero}"
                                                   itemLabel="Masculino"
                                                   itemValue="M"/>
                                    <b:radiobutton value="#{pacienteController.genero}"
                                                   itemLabel="Femenino"
                                                   itemValue="F"/>
                                </b:panelGrid>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="genero"/>
                            </b:column>
                        </b:row>
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Número de Teléfono" for="numTel"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Número de Teléfono" id="numTel"
                                             required="true"
                                             value="#{pacienteController.numTel}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="numTel"/>
                            </b:column>
                        </b:row>
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Fecha de nacimiento" for="fechaNaci"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:datepicker id="fechaNaci"
                                              required="true"
                                              value="#{pacienteController.fechaNaci}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="fechaNaci"/>
                            </b:column>
                        </b:row>
                        <b:row>
                            <b:column medium-screen="2"/>
                            <b:column medium-screen="6">
                                <b:commandButton value="Insertar"
                                                 action="#{pacienteController.insertaUser()}"
                                                 look="primary"
                                                 style="width: 33%"/>
                            </b:column>   
                        </b:row>    
                    </b:panel>
                </h:form> 
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/Paciente/listaPAdmin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">

    <h:head>
        <title>BD Pacientes</title>
    </h:head>
    <h:body>
        <ui:composition template="./../resources/plantillas/plantillaAdmin.xhtml">

            <ui:define name="content">
                 <h:form>
                     <b:dataTable value="#{pacienteController.pacientes}"
                                 var="paciente">
                        <b:dataTableColumn value="#{paciente.idPaciente}"
                                           width="8%"
                                           label="Identificación"/>
                        <b:dataTableColumn value="#{paciente.idHabitacion}"
                                           width="8%"
                                           label="Habitación"/>
                        <b:dataTableColumn value="#{paciente.nombreP}"
                                           width="12%"
                                           label="Nombre"/>
                        <b:dataTableColumn value="#{paciente.apellido1}"
                                           width="15%"
                                           label="Primer Apellido"/>
                        <b:dataTableColumn value="#{paciente.apellido2}"
                                           width="15%"
                                           label="Segundo Apellido"/>
                        <b:dataTableColumn value="#{paciente.direccPaciente}"
                                           width="10%"
                                           style="text-align: center"
                                           label="Dirección"/>
                        <b:dataTableColumn value="#{paciente.genero}"
                                           width="8%"
                                           style="text-align: center"
                                           label="Género"/>
                        <b:dataTableColumn value="#{paciente.numTel}"
                                           width="15%"
                                           style="text-align: center"
                                           label="Número de Teléfono."/>
                          <b:dataTableColumn value="#{paciente.fechaNaci}"
                                           width="16%"
                                           style="text-align: center"
                                           label="Fech.Naci"/>
                        
                    </b:dataTable>
                </h:form>
          </ui:define>

        </ui:composition>
    </h:body>
</html>

src/main/webapp/Paciente/listaPRespaldo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">

    <h:head>
        <title>BD Pacientes</title>
    </h:head>
    <h:body>
        <ui:composition template="./../resources/plantillas/plantillaRespaldo.xhtml">

            <ui:define name="content">
                 <h:form>
                     <b:dataTable value="#{pacienteController.pacientes}"
                                 var="paciente">
                        <b:dataTableColumn value="#{paciente.idPaciente}"
                                           width="8%"
                                           label="Identificación"/>
                        <b:dataTableColumn value="#{paciente.idHabitacion}"
                                           width="8%"
                                           label="Habitación"/>
                        <b:dataTableColumn value="#{paciente.nombreP}"
                                           width="12%"
                                           label="Nombre"/>
                        <b:dataTableColumn value="#{paciente.apellido1}"
                                           width="15%"
                                           label="Primer Apellido"/>
                        <b:dataTableColumn value="#{paciente.apellido2}"
                                           width="15%"
                                           label="Segundo Apellido"/>
                        <b:dataTableColumn value="#{paciente.direccPaciente}"
                                           width="10%"
                                           style="text-align: center"
                                           label="Dirección"/>
                        <b:dataTableColumn value="#{paciente.genero}"
                                           width="8%"
                                           style="text-align: center"
                                           label="Género"/>
                        <b:dataTableColumn value="#{paciente.numTel}"
                                           width="15%"
                                           style="text-align: center"
                                           label="Número de Teléfono."/>
                          <b:dataTableColumn value="#{paciente.fechaNaci}"
                                           width="16%"
                                           style="text-align: center"
                                           label="Fech.Naci"/>
                        
                    </b:dataTable>
                </h:form>
          </ui:define>

        </ui:composition>
    </h:body>
</html>

src/main/webapp/Paciente/listaPUser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">

    <h:head>
        <title>BD Pacientes</title>
    </h:head>
    <h:body>
        <ui:composition template="./../resources/plantillas/plantillaUser.xhtml">

            <ui:define name="content">
                 <h:form>
                     <b:dataTable value="#{pacienteController.pacientes}"
                                 var="paciente">
                        <b:dataTableColumn value="#{paciente.idPaciente}"
                                           width="8%"
                                           label="Identificación"/>
                        <b:dataTableColumn value="#{paciente.idHabitacion}"
                                           width="8%"
                                           label="Habitación"/>
                        <b:dataTableColumn value="#{paciente.nombreP}"
                                           width="12%"
                                           label="Nombre"/>
                        <b:dataTableColumn value="#{paciente.apellido1}"
                                           width="15%"
                                           label="Primer Apellido"/>
                        <b:dataTableColumn value="#{paciente.apellido2}"
                                           width="15%"
                                           label="Segundo Apellido"/>
                        <b:dataTableColumn value="#{paciente.direccPaciente}"
                                           width="10%"
                                           style="text-align: center"
                                           label="Dirección"/>
                        <b:dataTableColumn value="#{paciente.genero}"
                                           width="8%"
                                           style="text-align: center"
                                           label="Género"/>
                        <b:dataTableColumn value="#{paciente.numTel}"
                                           width="15%"
                                           style="text-align: center"
                                           label="Número de Teléfono."/>
                          <b:dataTableColumn value="#{paciente.fechaNaci}"
                                           width="16%"
                                           style="text-align: center"
                                           label="Fech.Naci"/>
                        
                    </b:dataTable>
                </h:form>
          </ui:define>

        </ui:composition>
    </h:body>
</html>