src/main/java/controller/DoctorController.java
package controller;

import gestion.DoctorGestion;
import gestion.PacienteGestion;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import java.io.Serializable;
import java.nio.file.Files;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletResponse;
import modelo.Doctor;


@Named(value = "doctorController")
@SessionScoped
public class DoctorController extends Doctor implements Serializable {

   
    public DoctorController() {
    }
     public String inserta(){
        
        if (DoctorGestion.insertar(this)){
            return "listaDAdmin.xhtml"; 
        }else{     
            FacesMessage mensaje = new FacesMessage(FacesMessage.SEVERITY_ERROR, 
            "Error", "Posible identificación duplicada");
            FacesContext.getCurrentInstance().addMessage("editaDoctoresForm:identificacion", mensaje);
            return "editaDAdmin.xhtml";
        }  
     }
     
  public String elimina(){
        
        if (DoctorGestion.eliminar(this)){
            return "listaDAdmin.xhtml";
        }else{
             FacesMessage mensaje = new FacesMessage(FacesMessage.SEVERITY_ERROR, 
            "Error", "Posible que el id no exista");
            FacesContext.getCurrentInstance().addMessage("editaDoctoresForm:identificacion", mensaje);
            return "editaDAdmin.xhtml";
        }
    }
  
   public List<Doctor> getDoctores(){
        
        return DoctorGestion.getDoctores();
    }     
   
       public String edita(String id){
        
        Doctor doc= DoctorGestion.getDoctor(id);
        if (doc!=null){
            
            this.setIdDoctor(doc.getIdDoctor());
            this.setNombreD(doc.getNombreD());
            this.setApellido1(doc.getApellido1());
            this.setApellido2(doc.getApellido2());
            this.setIdEspecialidad(doc.getIdEspecialidad());
            this.setNumTel(doc.getNumTel());
            return "editaDAdmin.xhtml";
        }else{
             FacesMessage mensaje = new FacesMessage(FacesMessage.SEVERITY_ERROR, 
            "Error", "Posible que el doctor no exista");
            FacesContext.getCurrentInstance().addMessage("editaDoctoresForm", mensaje);
            return "editaDAdmin.xhtml";
        }

    }
   
     public void respaldoDoctores(){
        
        String json  = PacienteGestion.GenerarJson();
        try{
            File f = new File (FacesContext.getCurrentInstance().getExternalContext().getRealPath("/respaldo")+"DoctoresDisponibles.zip");
            ZipOutputStream out = new ZipOutputStream (new FileOutputStream(f));
            ZipEntry e = new ZipEntry ("DoctoresDisponibles.json");
            try{     
                out.putNextEntry(e);
                byte[] data =json.getBytes();
                out.write(data,0,data.length);
                out.closeEntry();
                out.close();

                File zipPath = new File (FacesContext.getCurrentInstance().getExternalContext()
                .getRealPath("/respaldo")+"DoctoresDisponibles.zip");
                
                byte[] zip = Files.readAllBytes(zipPath.toPath());
                
                HttpServletResponse respuesta = (HttpServletResponse)
                    FacesContext.getCurrentInstance().getExternalContext().getResponse();
                
                ServletOutputStream sos = respuesta.getOutputStream();
            
                respuesta.setContentType("application/zip");
                respuesta.addHeader("Content-Disposition","attachment; filename=DoctoresDisponibles.zip");
                
                sos.write(zip);
                sos.flush();
                FacesContext.getCurrentInstance().responseComplete();
                
            }catch (IOException ex){
            }
        }
        catch(FileNotFoundException ex){
            
        }
    }
}

src/main/webapp/Doctor/editaDAdmin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">

    <body>
        <ui:composition template="./../resources/plantillas/plantillaAdmin.xhtml">
            <ui:define name="content">
                <h:form id="editaDoctoresForm">
                    <b:panel title="Doctores" look="primary">
                        <b:row tooltip="La identificación no se modifica">
                            <b:column medium-screen="2">
                                <h:outputLabel value="Identificación" for="identificacion"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Identificacion" id="identificacion"
                                             required="true"
                                             value="#{doctorController.idDoctor}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="identificacion"/>
                            </b:column>
                        </b:row>
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Nombre" for="nombre"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Nombre" id="nombre"
                                             required="true"
                                             value="#{doctorController.nombreD}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="habitacion"/>
                            </b:column>
                        </b:row>
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Primer Apellido" for="apellido1"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Primer Apellido" id="apellido1"
                                             required="true"
                                             value="#{doctorController.apellido1}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="apellido1"/>
                            </b:column>
                        </b:row>
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Segundo Apellido" for="apellido2"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Segundo Apellido" id="apellido2"
                                             required="true"
                                             value="#{doctorController.apellido2}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="apellido2"/>
                            </b:column>
                        </b:row>
                        <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Identificador Especialidad" for="id"/>
                            </b:column>
                            <b:column medium-screen="4">
                                 <b:inputText placeholder="Identificador Especialidad" id="id"
                                             required="true"
                                             value="#{doctorController.idEspecialidad}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="id"/>
                            </b:column>
                        </b:row>
                       
                         <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Número de Teléfono" for="numTel"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Número de Teléfono" id="numTel"
                                             required="true"
                                             value="#{doctorController.numTel}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="numTel"/>
                            </b:column>
                        </b:row>
                        
                        <b:row>
                            <b:column medium-screen="2"/>
                            <b:column medium-screen="6">
                                <b:commandButton value="Insertar"
                                                 action="#{doctorController.inserta()}"
                                                 look="primary"
                                                 style="width: 33%"/>
                                 <b:commandButton value="Eliminar"
                                                  action="#{doctorController.elimina()}"
                                                 look="danger"
                                                 style="width: 33%"/>
                            </b:column>   
                        </b:row>    
                    </b:panel>
                </h:form> 
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/Doctor/listaDAdmin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">

    <h:head>
        <title>BD Doctores</title>
    </h:head>
    <h:body>

        <ui:composition template="./../resources/plantillas/plantillaAdmin.xhtml">

            <ui:define name="content">
                 <h:form>

                    <b:dataTable value="#{doctorController.doctores}"
                                 var="doctor"
                                 excel="true"
                                 csv="true"
                                 pdf="true"
                                 columnVisibility="true"
                                 copy="true"
                                 print="true">
                        <b:dataTableColumn value="#{doctor.idDoctor}"
                                           width="8%"
                                           label="Identificación"/>
                        <b:dataTableColumn value="#{doctor.nombreD}"
                                           width="12%"
                                           label="Nombre"/>
                        <b:dataTableColumn value="#{doctor.apellido1}"
                                           width="15%"
                                           label="Primer Apellido"/>
                        <b:dataTableColumn value="#{doctor.apellido2}"
                                           width="15%"
                                           label="Segundo Apellido"/>
                        <b:dataTableColumn value="#{doctor.idEspecialidad}"
                                           width="8%"
                                           style="text-align: center"
                                           label="Especialidad"/>
                        <b:dataTableColumn value="#{doctor.numTel}"
                                           width="15%"
                                           style="text-align: center"
                                           label="Número de Teléfono"/>
                        <b:dataTableColumn width="10%"
                                           style="text-align: center"
                                           label="Acción">
                            <b:commandButton value="Editar"
                                      look="primary"
                                      action="#{doctorController.edita(doctor.idDoctor)}"/>
                        </b:dataTableColumn>
                    </b:dataTable>
                </h:form>
          </ui:define>

        </ui:composition>
    </h:body>
</html>

src/main/webapp/Doctor/listaDPrincipal.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">

    <h:head>
        <title>BD Doctores</title>
    </h:head>
    <h:body>

        <ui:composition template="./../resources/plantillas/plantilla.xhtml">

            <ui:define name="content">
                 <h:form>

                    <b:dataTable value="#{doctorController.doctores}"
                                 var="doctor"
                                 excel="true"
                                 csv="true"
                                 pdf="true"
                                 columnVisibility="true"
                                 copy="true"
                                 print="true">
                        <b:dataTableColumn value="#{doctor.idDoctor}"
                                           width="8%"
                                           label="Identificación"/>
                        <b:dataTableColumn value="#{doctor.nombreD}"
                                           width="12%"
                                           label="Nombre"/>
                        <b:dataTableColumn value="#{doctor.apellido1}"
                                           width="15%"
                                           label="Primer Apellido"/>
                        <b:dataTableColumn value="#{doctor.apellido2}"
                                           width="15%"
                                           label="Segundo Apellido"/>
                        <b:dataTableColumn value="#{doctor.idEspecialidad}"
                                           width="8%"
                                           style="text-align: center"
                                           label="Especialidad"/>
                        <b:dataTableColumn value="#{doctor.numTel}"
                                           width="15%"
                                           style="text-align: center"
                                           label="Número de Teléfono"/>
                    </b:dataTable>
                </h:form>
          </ui:define>

        </ui:composition>
    </h:body>
</html>

src/main/webapp/Doctor/listaDRespaldo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">

    <h:head>
        <title>BD Doctores</title>
    </h:head>
    <h:body>

        <ui:composition template="./../resources/plantillas/plantillaRespaldo.xhtml">

            <ui:define name="content">
                 <h:form>

                    <b:dataTable value="#{doctorController.doctores}"
                                 var="doctor"
                                 excel="true"
                                 csv="true"
                                 pdf="true"
                                 columnVisibility="true"
                                 copy="true"
                                 print="true">
                        <b:dataTableColumn value="#{doctor.idDoctor}"
                                           width="8%"
                                           label="Identificación"/>
                        <b:dataTableColumn value="#{doctor.nombreD}"
                                           width="12%"
                                           label="Nombre"/>
                        <b:dataTableColumn value="#{doctor.apellido1}"
                                           width="15%"
                                           label="Primer Apellido"/>
                        <b:dataTableColumn value="#{doctor.apellido2}"
                                           width="15%"
                                           label="Segundo Apellido"/>
                        <b:dataTableColumn value="#{doctor.idEspecialidad}"
                                           width="8%"
                                           style="text-align: center"
                                           label="Especialidad"/>
                        <b:dataTableColumn value="#{doctor.numTel}"
                                           width="15%"
                                           style="text-align: center"
                                           label="Número de Teléfono"/>
                    </b:dataTable>
                </h:form>
          </ui:define>

        </ui:composition>
    </h:body>
</html>

src/main/webapp/Doctor/listaDUser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">

    <h:head>
        <title>BD Doctores</title>
    </h:head>
    <h:body>

        <ui:composition template="./../resources/plantillas/plantillaUser.xhtml">

            <ui:define name="content">
                 <h:form>

                    <b:dataTable value="#{doctorController.doctores}"
                                 var="doctor"
                                 excel="true"
                                 csv="true"
                                 pdf="true"
                                 columnVisibility="true"
                                 copy="true"
                                 print="true">
                        <b:dataTableColumn value="#{doctor.idDoctor}"
                                           width="8%"
                                           label="Identificación"/>
                        <b:dataTableColumn value="#{doctor.nombreD}"
                                           width="12%"
                                           label="Nombre"/>
                        <b:dataTableColumn value="#{doctor.apellido1}"
                                           width="15%"
                                           label="Primer Apellido"/>
                        <b:dataTableColumn value="#{doctor.apellido2}"
                                           width="15%"
                                           label="Segundo Apellido"/>
                        <b:dataTableColumn value="#{doctor.idEspecialidad}"
                                           width="8%"
                                           style="text-align: center"
                                           label="Especialidad"/>
                        <b:dataTableColumn value="#{doctor.numTel}"
                                           width="15%"
                                           style="text-align: center"
                                           label="Número de Teléfono"/>
                        
                    </b:dataTable>
                    
                </h:form>
          </ui:define>

        </ui:composition>
    </h:body>
</html>