src/main/java/controller/CitasController.java
package controller;

import gestion.CitasGestion;
import gestion.PacienteGestion;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.nio.file.Files;
import java.util.List;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletResponse;
import modelo.Citas;


@Named(value = "citasController")
@SessionScoped

public class CitasController extends Citas implements Serializable {

    public CitasController() {
    }
   public String insertaAdmin(){
        
        if (CitasGestion.insertar(this)){
            
            return "confirmacionAdmin.xhtml";
            
        }else{
          
            FacesMessage mensaje = new FacesMessage(FacesMessage.SEVERITY_ERROR, 
            "Error", "Posible identificación duplicada o no existe paciente registrado");
            FacesContext.getCurrentInstance().addMessage("citaForm:identificacion", mensaje);
            return "tramitaCAdmin.xhtml";
        }
        
    }
     public String insertaUser(){
        
        if (CitasGestion.insertar(this)){
            
            return "confirmacionUser.xhtml";
            
        }else{
          
            FacesMessage mensaje = new FacesMessage(FacesMessage.SEVERITY_ERROR, 
            "Error", "Posible identificación duplicada o no existe paciente registrado");
            FacesContext.getCurrentInstance().addMessage("citaForm:identificacion", mensaje);
            return "tramitaCUser.xhtml";
        }
        
    }

    public List<Citas> getCitas(){
        
        return CitasGestion.getCitas();
        
    }  
    
     public void respaldoCitas(){
        
        String json  = PacienteGestion.GenerarJson();
        try{
            File f = new File (FacesContext.getCurrentInstance().getExternalContext().getRealPath("/Respaldos")+"CitasRegistradas.zip");
            ZipOutputStream out = new ZipOutputStream (new FileOutputStream(f));
            ZipEntry e = new ZipEntry ("CitasRegistradas.json");
            try{     
                out.putNextEntry(e);
                byte[] data =json.getBytes();
                out.write(data,0,data.length);
                out.closeEntry();
                out.close();

                File zipPath = new File (FacesContext.getCurrentInstance().getExternalContext()
                .getRealPath("/Respaldos")+"CitasRegistradas.zip");
                
                byte[] zip = Files.readAllBytes(zipPath.toPath());
                
                HttpServletResponse respuesta = (HttpServletResponse)
                    FacesContext.getCurrentInstance().getExternalContext().getResponse();
                
                ServletOutputStream sos = respuesta.getOutputStream();
            
                respuesta.setContentType("application/zip");
                respuesta.addHeader("Content-Disposition","attachment; filename=CitasRegistradas.zip");
                
                sos.write(zip);
                sos.flush();
                FacesContext.getCurrentInstance().responseComplete();
                
            }catch (IOException ex){
            }
        }
        catch(FileNotFoundException ex){
            
        }
    }
}

src/main/webapp/Cita/confirmacionAdmin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <body>
        <ui:composition template="../resources/plantillas/plantillaAdmin.xhtml">
            <ui:define name="content">
                <b:container fluid="true">
                    <b:panel title="El registro de cita fue exitoso" look="primary">
                        <b:row>
                            <b:column medium-screen="3">
                                <h:outputLabel value="Mantenga este código para futuras gestiones de su cita"/>
                            </b:column>
                            <b:column medium-screen="3">
                                <p:barcode value="#{citasController.toStringQR()}" type="qr" width="400px"/>
                                
                            </b:column>
                        </b:row>
                    </b:panel>
                </b:container>
            </ui:define>
        </ui:composition>
      </body>  
</html>

src/main/webapp/Cita/confirmacionUser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <body>
        <ui:composition template="../resources/plantillas/plantillaUser.xhtml">
            <ui:define name="content">
                <b:container fluid="true">
                    <b:panel title="El registro de cita fue exitoso" look="primary">
                        <b:row>
                            <b:column medium-screen="3">
                                <h:outputLabel value="Mantenga este código para futuras gestiones de su cita"/>
                            </b:column>
                            <b:column medium-screen="3">
                                <p:barcode value="#{citasController.toStringQR()}" type="qr" width="400px"/>
                                
                            </b:column>
                        </b:row>
                    </b:panel>
                </b:container>
            </ui:define>
        </ui:composition>
      </body>  
</html>

src/main/webapp/Cita/listaCAdmin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">

    <h:head>
        <title>BD Citas</title>
    </h:head>
    <h:body>

        <ui:composition template="./../resources/plantillas/plantillaAdmin.xhtml">

            <ui:define name="content">
                 <h:form>

                     <b:dataTable value="#{citasController.citas}"
                                 var="cita"
                                 excel="true"
                                 csv="true"
                                 pdf="true"
                                 columnVisibility="true"
                                 copy="true"
                                 print="true">
                        <b:dataTableColumn value="#{cita.idCita}"
                                           width="8%"
                                           label="Identificación Cita"/>
                        <b:dataTableColumn value="#{cita.idPaciente}"
                                           width="15%"
                                           label="Identificación Paciente"/>
                        <b:dataTableColumn value="#{cita.idDoctor}"
                                           width="15%"
                                           label="Identificación Doctor"/>
                        <b:dataTableColumn value="#{cita.fechaCita}"
                                           width="15%"
                                           label="Fecha"/>
                        <b:dataTableColumn value="#{cita.idServicio}"
                                           width="8%"
                                           style="text-align: center"
                                           label="Servicio Médico"/>
                        <b:dataTableColumn value="#{cita.idHabitacion}"
                                           width="10%"
                                           style="text-align: center"
                                           label="Habitación"/>
                    </b:dataTable>
                    
                </h:form>
          </ui:define>

        </ui:composition>
    </h:body>
</html>

src/main/webapp/Cita/listaCRespaldo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">

    <h:head>
        <title>BD Citas</title>
    </h:head>
    <h:body>

        <ui:composition template="./../resources/plantillas/plantillaRespaldo.xhtml">

            <ui:define name="content">
                 <h:form>

                     <b:dataTable value="#{citasController.citas}"
                                 var="cita"
                                 excel="true"
                                 csv="true"
                                 pdf="true"
                                 columnVisibility="true"
                                 copy="true"
                                 print="true">
                        <b:dataTableColumn value="#{cita.idCita}"
                                           width="8%"
                                           label="Identificación Cita"/>
                        <b:dataTableColumn value="#{cita.idPaciente}"
                                           width="15%"
                                           label="Identificación Paciente"/>
                        <b:dataTableColumn value="#{cita.idDoctor}"
                                           width="15%"
                                           label="Identificación Doctor"/>
                        <b:dataTableColumn value="#{cita.fechaCita}"
                                           width="15%"
                                           label="Fecha"/>
                        <b:dataTableColumn value="#{cita.idServicio}"
                                           width="8%"
                                           style="text-align: center"
                                           label="Servicio Médico"/>
                        <b:dataTableColumn value="#{cita.idHabitacion}"
                                           width="10%"
                                           style="text-align: center"
                                           label="Habitación"/>
                    </b:dataTable>
                    
                </h:form>
          </ui:define>

        </ui:composition>
    </h:body>
</html>

src/main/webapp/Cita/tramitaCAdmin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">

    <body>
        <ui:composition template="../resources/plantillas/plantillaAdmin.xhtml">
            <ui:define name="content">
                <h:form id="citaForm">
                    <b:panel title="Registro Cita" look="primary">
                        
                        <b:row tooltip="La identificación no se modifica">
                            <b:column medium-screen="2">
                                <h:outputLabel value="Identificación Paciente" for="identificacion"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Identificacion del Paciente" id="identificacion"
                                             required="true"
                                             value="#{citasController.idPaciente}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="identificacion"/>
                            </b:column>
                        </b:row>

                            <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Identificación Doctor" for="doct"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Identificacion del Doctor" id="doct"
                                             required="true"
                                             value="#{citasController.idDoctor}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="doct"/>
                            </b:column>
                        </b:row>
                        
                        <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Servicio Médico" for="servicio"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:panelGrid size="" columns="3">
                                    <b:radiobutton value="#{citasController.idServicio}"
                                                   itemLabel="Consulta Médica"
                                                   itemValue="1"/>
                                    <b:radiobutton value="#{citasController.idServicio}"
                                                   itemLabel="Radiografía"
                                                   itemValue="2"/>
                                    <b:radiobutton value="#{citasController.idServicio}"
                                                   itemLabel="Ultrasonido"
                                                   itemValue="3"/>
                                </b:panelGrid>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="servicio"/>
                            </b:column>
                        </b:row>

                        <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Habitación" for="habitacion"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:panelGrid size="" columns="4">
                                    <b:radiobutton value="#{citasController.idHabitacion}"
                                                   itemLabel="Suite   Piso 1"
                                                   itemValue="A-100"/>
                                    <b:radiobutton value="#{citasController.idHabitacion}"
                                                   itemLabel="Estándar   Piso 1"
                                                   itemValue="A-201"/>
                                    <b:radiobutton value="#{citasController.idHabitacion}"
                                                   itemLabel="Suite   Piso 2"
                                                   itemValue="B-121"/>
                                    <b:radiobutton value="#{citasController.idHabitacion}"
                                                   itemLabel="Estándar   Piso 3"
                                                   itemValue="C-215"/>
                                </b:panelGrid> 

                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="habitacion"/>
                            </b:column>
                        </b:row>

                       

                        <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Fecha de Cita" for="fechaCita"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:datepicker id="fechaCita"
                                              required="true"
                                              value="#{citasController.fechaCita}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="fechaCita"/>
                            </b:column>
                        </b:row>
                        
                        <b:row>
                            <b:column medium-screen="2"/>
                            <b:column medium-screen="6">
                                <b:commandButton value="Insertar"
                                                 action="#{citasController.insertaAdmin()}"
                                                 look="primary"
                                                 style="width: 33%"/>
                            </b:column>   
                        </b:row>    
                    </b:panel>
                </h:form> 
            </ui:define>
        </ui:composition>
    </body>
</html>


  
 

src/main/webapp/Cita/tramitaCUser.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui">

    <body>
        <ui:composition template="../resources/plantillas/plantillaUser.xhtml">
            <ui:define name="content">
                <h:form id="citaForm">
                    <b:panel title="Registro Cita" look="primary">
                        
                        <b:row tooltip="La identificación no se modifica">
                            <b:column medium-screen="2">
                                <h:outputLabel value="Identificación Paciente" for="identificacion"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Identificacion del Paciente" id="identificacion"
                                             required="true"
                                             value="#{citasController.idPaciente}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="identificacion"/>
                            </b:column>
                        </b:row>

                            <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Identificación Doctor" for="doct"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:inputText placeholder="Identificacion del Doctor" id="doct"
                                             required="true"
                                             value="#{citasController.idDoctor}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="doct"/>
                            </b:column>
                        </b:row>
                        
                        <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Servicio Médico" for="servicio"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:panelGrid size="" columns="3">
                                    <b:radiobutton value="#{citasController.idServicio}"
                                                   itemLabel="Consulta Médica"
                                                   itemValue="1"/>
                                    <b:radiobutton value="#{citasController.idServicio}"
                                                   itemLabel="Radiografía"
                                                   itemValue="2"/>
                                    <b:radiobutton value="#{citasController.idServicio}"
                                                   itemLabel="Ultrasonido"
                                                   itemValue="3"/>
                                </b:panelGrid>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="servicio"/>
                            </b:column>
                        </b:row>

                        <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Habitación" for="habitacion"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:panelGrid size="" columns="4">
                                    <b:radiobutton value="#{citasController.idHabitacion}"
                                                   itemLabel="Suite   Piso 1"
                                                   itemValue="A-100"/>
                                    <b:radiobutton value="#{citasController.idHabitacion}"
                                                   itemLabel="Estándar   Piso 1"
                                                   itemValue="A-201"/>
                                    <b:radiobutton value="#{citasController.idHabitacion}"
                                                   itemLabel="Suite   Piso 2"
                                                   itemValue="B-121"/>
                                    <b:radiobutton value="#{citasController.idHabitacion}"
                                                   itemLabel="Estándar   Piso 3"
                                                   itemValue="C-215"/>
                                </b:panelGrid> 

                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="habitacion"/>
                            </b:column>
                        </b:row>

                       

                        <b:row>
                            <b:column medium-screen="2">
                                <h:outputLabel value="Fecha de Cita" for="fechaCita"/>
                            </b:column>
                            <b:column medium-screen="4">
                                <b:datepicker id="fechaCita"
                                              required="true"
                                              value="#{citasController.fechaCita}"/>
                            </b:column>
                            <b:column medium-screen="6" style-class="message">
                                <b:message for="fechaCita"/>
                            </b:column>
                        </b:row>
                        
                        <b:row>
                            <b:column medium-screen="2"/>
                            <b:column medium-screen="6">
                                <b:commandButton value="Insertar"
                                                 action="#{citasController.insertaUser()}"
                                                 look="primary"
                                                 style="width: 33%"/>
                            </b:column>   
                        </b:row>    
                    </b:panel>
                </h:form> 
            </ui:define>
        </ui:composition>
    </body>
</html>


  
 